version: '3.7'

services:
  jekyll_dev:
    image: gravitee.io/jekyll:0.0.1-dev
    env_file: ./container/dev/.env
    build:
      context: container/dev
      dockerfile: Dockerfile
      args:
        GIT_COMMIT_ID: $GIT_COMMIT_ID
    container_name: jekyll_dev
    # image: jekyll/jekyll:latest
    # command: jekyll serve --watch --force_polling --verbose
    ports:
      - 0.0.0.0:4000:4000
    # volumes:
      # - .:/srv/jekyll
  jekyll_nginx:
    image: gravitee.io/jekyll-nginx:0.0.1-github
    env_file: ./container/gravitee/.env
    build:
      context: container/gravitee/gravitee-docs-repo/
      dockerfile: Dockerfile
      args:
        GIT_COMMIT_ID: $GIT_COMMIT_ID
    container_name: jekyll_nginx
    # image: jekyll/jekyll:latest
    # command: jekyll serve --watch --force_polling --verbose
    ports:
      - 0.0.0.0:8080:80
    volumes:
      - $PWD/jekyll_nginx_project:/src/
  jekyll_dev_repaired:
    image: gravitee.io/jekyll:0.0.1-dev-repaired
    env_file: ./container/dev-repaired/.env
    build:
      context: container/dev-repaired/gravitee-docs-repo/
      dockerfile: Dockerfile
      args:
        GIT_COMMIT_ID: $GIT_COMMIT_ID
    container_name: jekyll_dev_repaired
    # image: jekyll/jekyll:latest
    # command: jekyll serve --watch --force_polling --verbose
    ports:
      - 0.0.0.0:4001:4000
    # volumes:
      # - .:/srv/jekyll
  jekyll_nginx_repaired:
    image: gravitee.io/jekyll-nginx:0.0.1-github
    env_file: ./container/gravitee-repaired/.env
    build:
      context: container/gravitee-repaired/
      dockerfile: Dockerfile
      args:
        GIT_COMMIT_ID: $GIT_COMMIT_ID
    container_name: jekyll_nginx_repaired
    # image: jekyll/jekyll:latest
    # command: jekyll serve --watch --force_polling --verbose
    ports:
      - 0.0.0.0:8081:80
    # volumes:
      # - .:/srv/jekyll
