version: '3.7'

services:
  jekyll_dev:
    image: gravitee.io/jekyll:0.0.1-dev
    env_file: ./container/dev/.env
    build:
      context: container/dev
      dockerfile: container/dev/Dockerfile
      args:
        GIT_COMMIT_ID: $GIT_COMMIT_ID
    container_name: jekyll_dev
    # image: jekyll/jekyll:latest
    # command: jekyll serve --watch --force_polling --verbose
    ports:
      - 0.0.0.0:4000:4000
    # volumes:
      # - .:/srv/jekyll
  jekyll_nginx:
    image: gravitee.io/jekyll-nginx:0.0.1-github
    env_file: ./container/gravitee/.env
    build:
      context: container/gravitee
      dockerfile: container/gravitee/Dockerfile
      args:
        GIT_COMMIT_ID: $GIT_COMMIT_ID
    container_name: jekyll_dev
    # image: jekyll/jekyll:latest
    # command: jekyll serve --watch --force_polling --verbose
    ports:
      - 0.0.0.0:8080:80
    # volumes:
      # - .:/srv/jekyll
