version: '3.7'

services:
  jekyll:
    image: gravitee.io/jekyll:0.0.1
    # image: jekyll/jekyll:latest
    # command: jekyll serve --watch --force_polling --verbose
    ports:
      - 0.0.0.0:4000:4000
    # volumes:
      # - .:/srv/jekyll
